export const prompts = [
  "The oldest player.",
  "The youngest player.",
  "The player whose name comes first alphabetically.",
  "The player whose name comes last alphabetically.",
  "The player with the longest first name in length.",
  "The player with the shortest first name in length.",
  "The player with the longest last name in length.",
  "The player with the shortest last name in length.",
  "The player who brought the game.",
  "The player who purchased the game.",
  "The player who owns the game.",
  "The player closest to the left of the game owner.",
  "The player closest to the right of the game owner.",
  "The player farthest from the game owner.",
  "The player who is teaching the game.",
  "The player who has played the game the most.",
  "The player who has played the game the least.",
  "The player using this device.",
  "The player who is closest to the person using this device.",
  "The player who is farthest from the person using this device.",
  "The player who arrived last.",
  "The player who setup more of the game.",
  "The player who won the previous game.",
  "The player who lost the previous game.",
  "The player who has the most board games in their collection.",
  "The player who has the least board games in their collection.",
  "The player who is currently on their phone. If no one is on their phone, then the player using this device.",
  "The player who initiated the game night.",
  "The player as determined by the official game's rules.",
  "The player who wins a die roll of the highest number.",
  "The player who wins a die roll of the lowest number.",
  "The player who last touched the rule book.",
  "The player who last touched the game board.",
  "The player who last touched the game box.",
  "The player who is currently holding any game piece.",
  "The player who travelled the farthest distance to attend the game night.",
  "The player who travelled the least distance to attend the game night.",
];
